import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, doc, getDoc, updateDoc, deleteDoc, setDoc, serverTimestamp, query, orderBy } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import { firebaseConfig } from "../firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s);
const loginPanel=$("#loginPanel"),dashboard=$("#dashboard"),loginForm=$("#loginForm"),productForm=$("#productForm"),productsList=$("#productsList"),payments=$("#payments"),paymentEditor=$("#paymentEditor"),settingsForm=$("#settingsForm");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function isAdmin(u){return !!u&&(await getDoc(doc(db,"admins",u.uid))).exists()}
loginForm.addEventListener("submit",async e=>{e.preventDefault();$("#loginMessage").textContent="جارٍ تسجيل الدخول...";try{const c=await signInWithEmailAndPassword(auth,$("#loginEmail").value,$("#loginPassword").value);if(!await isAdmin(c.user)){await signOut(auth);throw Error("هذا الحساب ليس لديه صلاحية الإدارة.")}$("#loginMessage").textContent="تم الدخول بنجاح ✅"}catch(x){$("#loginMessage").textContent="تعذر الدخول. تأكد من البريد وكلمة المرور."}});
$("#logoutBtn").onclick=()=>signOut(auth);$("#refreshProducts").onclick=loadProducts;
function imageData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(Error("تعذر قراءة الصورة"));r.onload=()=>{const i=new Image();i.onload=()=>{const max=1000,s=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(i.width*s));c.height=Math.max(1,Math.round(i.height*s));c.getContext("2d").drawImage(i,0,0,c.width,c.height);const d=c.toDataURL("image/jpeg",.68);if(d.length>780000)reject(Error("الصورة كبيرة جدًا؛ اختر صورة أصغر."));else resolve(d)};i.onerror=()=>reject(Error("ملف الصورة غير صالح"));i.src=r.result};r.readAsDataURL(file)})}
$("#image").onchange=e=>{const f=e.target.files[0],p=$("#imagePreview");if(f){p.src=URL.createObjectURL(f);p.style.display="block"}else p.style.display="none"};
onAuthStateChanged(auth,async u=>{if(!u){loginPanel.hidden=false;dashboard.hidden=true;return}if(!await isAdmin(u)){await signOut(auth);return}loginPanel.hidden=true;dashboard.hidden=false;$("#adminEmail").textContent=u.email;await Promise.all([loadProducts(),loadPayments(),loadSettings()])});
productForm.addEventListener("submit",async e=>{e.preventDefault();if(!await isAdmin(auth.currentUser))return;const f=new FormData(productForm);try{let imageUrl=(f.get("imageUrl")||"").trim();const file=f.get("image");if(file&&file.size)imageUrl=await imageData(file);const payload={name:f.get("name").trim(),description:(f.get("description")||"").trim(),price:Number(f.get("price")),oldPrice:f.get("oldPrice")?Number(f.get("oldPrice")):null,category:f.get("category"),imageUrl,active:f.get("active")==="on",updatedAt:serverTimestamp()};if(productForm.dataset.editId){await updateDoc(doc(db,"products",productForm.dataset.editId),payload);delete productForm.dataset.editId;$("#productMessage").textContent="تم تعديل المنتج بنجاح ✅"}else{payload.createdAt=serverTimestamp();payload.createdBy=auth.currentUser.uid;await addDoc(collection(db,"products"),payload);$("#productMessage").textContent="تم حفظ المنتج والصورة بنجاح ✅"}productForm.reset();$("#imagePreview").style.display="none";$("#productForm button[type=submit]").textContent="حفظ المنتج";loadProducts()}catch(x){console.error(x);$("#productMessage").textContent=x.message||"حدث خطأ."}});
async function loadProducts(){productsList.innerHTML="جارٍ التحميل...";const s=await getDocs(query(collection(db,"products"),orderBy("createdAt","desc")));if(s.empty){productsList.innerHTML='<p class="muted">لا توجد منتجات بعد.</p>';return}productsList.innerHTML="";s.forEach(d=>{const p=d.data(),r=document.createElement("div");r.className="payment product-admin-row";r.innerHTML=`<div class="admin-product-main">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(p.name)}">`:'<div class="no-thumb">📦</div>'}<div><strong>${esc(p.name)}</strong><br><small>${esc(p.category||"")} — $${Number(p.price||0).toFixed(2)} — ${p.active?'ظاهر':'مخفي'}</small></div></div><div class="admin-actions"><button class="btn ghost small-btn" data-edit-product="${d.id}">تعديل</button><button class="btn ghost small-btn" data-toggle-product="${d.id}">${p.active?'إخفاء':'إظهار'}</button><button class="btn ghost small-btn" data-delete-product="${d.id}">حذف</button></div>`;productsList.appendChild(r)})}
productsList.onclick=async e=>{const ed=e.target.closest("[data-edit-product]"),t=e.target.closest("[data-toggle-product]"),d=e.target.closest("[data-delete-product]");if(ed){const id=ed.dataset.editProduct,s=await getDoc(doc(db,"products",id)),p=s.data();productForm.dataset.editId=id;productForm.name.value=p.name||"";productForm.description.value=p.description||"";productForm.price.value=p.price??"";productForm.oldPrice.value=p.oldPrice??"";productForm.category.value=p.category||"Templates";productForm.imageUrl.value=p.imageUrl?.startsWith("data:")?"":(p.imageUrl||"");productForm.active.checked=p.active!==false;$("#productForm button[type=submit]").textContent="حفظ التعديل";$("#productMessage").textContent="✏️ عدّل المنتج ثم اضغط حفظ التعديل.";window.scrollTo({top:0,behavior:"smooth"});return}if(t){const r=doc(db,"products",t.dataset.toggleProduct),s=await getDoc(r);await updateDoc(r,{active:!s.data().active,updatedAt:serverTimestamp()});loadProducts()}if(d&&confirm("هل تريد حذف هذا المنتج؟")){await deleteDoc(doc(db,"products",d.dataset.deleteProduct));loadProducts()}};
async function loadPayments(){payments.innerHTML="جارٍ التحميل...";const s=await getDocs(collection(db,"paymentMethods"));payments.innerHTML="";if(s.empty){payments.innerHTML='<p class="muted">لا توجد وسائل دفع بعد.</p>'}s.forEach(d=>{const p=d.data(),r=document.createElement("div");r.className="payment";r.innerHTML=`<strong>${esc(p.name)}</strong><br><small>${p.enabled?'مفعلة':'معطلة'}${p.account?' — '+esc(p.account):''}</small><div class="payment-actions"><button class="btn ghost small-btn" data-edit-payment="${d.id}">تعديل</button><button class="btn ghost small-btn" data-toggle-payment="${d.id}">${p.enabled?'تعطيل':'تفعيل'}</button><button class="btn ghost small-btn" data-delete-payment="${d.id}">حذف</button></div>`;payments.appendChild(r)});renderPaymentEditor(s)}
function renderPaymentEditor(s){paymentEditor.innerHTML="";s.forEach(d=>{const p=d.data(),box=document.createElement("div");box.className="editor-box";box.innerHTML=`<strong>${esc(p.name)}</strong><div class="two"><input data-field="name" value="${esc(p.name||"")}" placeholder="اسم وسيلة الدفع"><input data-field="account" value="${esc(p.account||"")}" placeholder="رقم الحساب / الهاتف / المحفظة"></div><input data-field="instructions" value="${esc(p.instructions||"")}" placeholder="تعليمات الدفع"><label class="check"><input data-field="enabled" type="checkbox" ${p.enabled?'checked':''}> مفعلة</label><button class="btn primary small-btn" data-save-payment="${d.id}">حفظ التعديل</button>`;paymentEditor.appendChild(box)})}
$("#addPayment").onclick=async()=>{const name=prompt("اسم وسيلة الدفع:");if(!name?.trim())return;const account=prompt("رقم الحساب / الهاتف / عنوان المحفظة:")||"";const instructions=prompt("تعليمات الدفع للعميل:")||"";await addDoc(collection(db,"paymentMethods"),{name:name.trim(),account:account.trim(),instructions:instructions.trim(),enabled:true,createdAt:serverTimestamp()});loadPayments()};
payments.onclick=async e=>{const ed=e.target.closest("[data-edit-payment]"),t=e.target.closest("[data-toggle-payment]"),d=e.target.closest("[data-delete-payment]");if(ed){const box=[...paymentEditor.children].find(x=>x.querySelector(`[data-save-payment='${ed.dataset.editPayment}']`));if(box)box.scrollIntoView({behavior:"smooth",block:"center"})}if(t){const r=doc(db,"paymentMethods",t.dataset.togglePayment),s=await getDoc(r);await updateDoc(r,{enabled:!s.data().enabled});loadPayments()}if(d&&confirm("هل تريد حذف وسيلة الدفع؟")){await deleteDoc(doc(db,"paymentMethods",d.dataset.deletePayment));loadPayments()}};
paymentEditor.onclick=async e=>{const b=e.target.closest("[data-save-payment]");if(!b)return;const box=b.closest(".editor-box");await updateDoc(doc(db,"paymentMethods",b.dataset.savePayment),{name:box.querySelector('[data-field="name"]').value.trim(),account:box.querySelector('[data-field="account"]').value.trim(),instructions:box.querySelector('[data-field="instructions"]').value.trim(),enabled:box.querySelector('[data-field="enabled"]').checked,updatedAt:serverTimestamp()});loadPayments()};
settingsForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(settingsForm);await setDoc(doc(db,"settings","store"),{storeName:f.get("storeName").trim(),tagline:f.get("tagline").trim(),whatsapp:f.get("whatsapp").trim(),email:f.get("email").trim(),heroTitle:f.get("heroTitle").trim(),heroDescription:f.get("heroDescription").trim(),contactTitle:f.get("contactTitle").trim(),logoText:f.get("logoText").trim(),currency:"USD",updatedAt:serverTimestamp()},{merge:true});$("#settingsMessage").textContent="تم حفظ جميع الإعدادات ✅"};
async function loadSettings(){const s=await getDoc(doc(db,"settings","store"));const p=s.exists()?s.data():{};settingsForm.storeName.value=p.storeName||"DIGITAL EMDZ";settingsForm.tagline.value=p.tagline||"Discover • Create • Grow";settingsForm.whatsapp.value=p.whatsapp||"+213770913494";settingsForm.email.value=p.email||"digitalemdz@gmail.com";settingsForm.heroTitle.value=p.heroTitle||"اكتشف عالم المنتجات الرقمية";settingsForm.heroDescription.value=p.heroDescription||"أدوات وقوالب وملفات رقمية تساعدك على العمل بشكل أسرع، تنظيم أفكارك، وإنجاز المزيد.";settingsForm.contactTitle.value=p.contactTitle||"تواصل معنا";settingsForm.logoText.value=p.logoText||"DIGITAL EMDZ"}
