import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore,collection,addDoc,getDocs,doc,getDoc,updateDoc,deleteDoc,setDoc,serverTimestamp,query,orderBy } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import { firebaseConfig } from "../firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s),loginPanel=$("#loginPanel"),dashboard=$("#dashboard"),loginForm=$("#loginForm"),productForm=$("#productForm"),productsList=$("#productsList"),payments=$("#payments"),settingsForm=$("#settingsForm");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function isAdmin(u){return !!u&&(await getDoc(doc(db,"admins",u.uid))).exists()}
loginForm.addEventListener("submit",async e=>{e.preventDefault();$("#loginMessage").textContent="جارٍ تسجيل الدخول...";try{const c=await signInWithEmailAndPassword(auth,$("#loginEmail").value,$("#loginPassword").value);if(!await isAdmin(c.user)){await signOut(auth);throw Error("هذا الحساب ليس لديه صلاحية الإدارة.")}$("#loginMessage").textContent="تم الدخول بنجاح ✅"}catch(x){$("#loginMessage").textContent=x.message||"تعذر تسجيل الدخول."}});
$("#logoutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){loginPanel.hidden=false;dashboard.hidden=true;return}if(!await isAdmin(u)){await signOut(auth);return}loginPanel.hidden=true;dashboard.hidden=false;$("#adminEmail").textContent=u.email;await Promise.all([loadProducts(),loadPayments(),loadSettings()])});
function imageData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(Error("تعذر قراءة الصورة"));r.onload=()=>{const i=new Image();i.onload=()=>{const m=900,s=Math.min(1,m/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=Math.round(i.width*s);c.height=Math.round(i.height*s);c.getContext("2d").drawImage(i,0,0,c.width,c.height);const d=c.toDataURL("image/jpeg",.72);if(d.length>900000)reject(Error("الصورة ما زالت كبيرة. اختر صورة أصغر."));else resolve(d)};i.onerror=()=>reject(Error("ملف الصورة غير صالح"));i.src=r.result};r.readAsDataURL(file)})}
productForm.addEventListener("submit",async e=>{e.preventDefault();if(!await isAdmin(auth.currentUser))return;const f=new FormData(productForm);try{let imageUrl=(f.get("imageUrl")||"").trim();const file=f.get("image");if(file&&file.size)imageUrl=await imageData(file);await addDoc(collection(db,"products"),{name:f.get("name").trim(),description:(f.get("description")||"").trim(),price:Number(f.get("price")),oldPrice:f.get("oldPrice")?Number(f.get("oldPrice")):null,category:f.get("category"),imageUrl,active:true,createdAt:serverTimestamp(),createdBy:auth.currentUser.uid});productForm.reset();$("#productMessage").textContent="تم حفظ المنتج والصورة بنجاح ✅";loadProducts()}catch(x){console.error(x);$("#productMessage").textContent=x.message||"حدث خطأ."}});
async function loadProducts(){productsList.innerHTML="جارٍ التحميل...";const s=await getDocs(query(collection(db,"products"),orderBy("createdAt","desc")));if(s.empty){productsList.innerHTML="لا توجد منتجات.";return}productsList.innerHTML="";s.forEach(d=>{const p=d.data(),r=document.createElement("div");r.className="payment product-admin-row";r.innerHTML=`<div class="admin-product-main">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="">`:'<div class="no-thumb">📦</div>'}<div><strong>${esc(p.name)}</strong><br><small>${esc(p.category||"")} — $${Number(p.price||0).toFixed(2)} — ${p.active?'ظاهر':'مخفي'}</small></div></div><div><button class="btn ghost" data-toggle="${d.id}">${p.active?'إخفاء':'إظهار'}</button> <button class="btn ghost" data-delete="${d.id}">حذف</button></div>`;productsList.appendChild(r)})}
productsList.onclick=async e=>{const t=e.target.closest("[data-toggle]"),d=e.target.closest("[data-delete]");if(t){const r=doc(db,"products",t.dataset.toggle),s=await getDoc(r);await updateDoc(r,{active:!s.data().active});loadProducts()}if(d&&confirm("هل تريد حذف هذا المنتج؟")){await deleteDoc(doc(db,"products",d.dataset.delete));loadProducts()}};
async function loadPayments(){payments.innerHTML="جارٍ التحميل...";let s=await getDocs(collection(db,"paymentMethods"));if(s.empty){for(const name of ["BaridiMob","CCP","CIB","Binance","RedotPay","PayPal"])await addDoc(collection(db,"paymentMethods"),{name,account:"",instructions:"أضف بيانات الدفع من الإدارة.",enabled:true,createdAt:serverTimestamp()});s=await getDocs(collection(db,"paymentMethods"))}payments.innerHTML="";s.forEach(d=>{const p=d.data(),r=document.createElement("div");r.className="payment";r.innerHTML=`<strong>${esc(p.name)}</strong><br><small>${p.enabled?'مفعلة':'معطلة'}${p.account?' — '+esc(p.account):''}</small><div><button class="btn ghost" data-edit="${d.id}">تعديل</button> <button class="btn ghost" data-pt="${d.id}">${p.enabled?'تعطيل':'تفعيل'}</button> <button class="btn ghost" data-pd="${d.id}">حذف</button></div>`;payments.appendChild(r)})}
$("#addPayment").onclick=async()=>{const name=prompt("اسم وسيلة الدفع:");if(!name?.trim())return;const account=prompt("رقم الحساب / الهاتف / عنوان المحفظة:")||"";const instructions=prompt("تعليمات الدفع للعميل:")||"";await addDoc(collection(db,"paymentMethods"),{name:name.trim(),account:account.trim(),instructions:instructions.trim(),enabled:true,createdAt:serverTimestamp()});loadPayments()};
payments.onclick=async e=>{const ed=e.target.closest("[data-edit]"),t=e.target.closest("[data-pt]"),d=e.target.closest("[data-pd]");if(ed){const r=doc(db,"paymentMethods",ed.dataset.edit),s=await getDoc(r),p=s.data();const name=prompt("اسم وسيلة الدفع:",p.name||"");if(!name?.trim())return;const account=prompt("رقم الحساب / الهاتف / المحفظة:",p.account||"");const instructions=prompt("تعليمات الدفع:",p.instructions||"");await updateDoc(r,{name:name.trim(),account:(account??p.account??"").trim(),instructions:(instructions??p.instructions??"").trim()});loadPayments()}if(t){const r=doc(db,"paymentMethods",t.dataset.pt),s=await getDoc(r);await updateDoc(r,{enabled:!s.data().enabled});loadPayments()}if(d&&confirm("هل تريد حذف وسيلة الدفع؟")){await deleteDoc(doc(db,"paymentMethods",d.dataset.pd));loadPayments()}};
settingsForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(settingsForm);await setDoc(doc(db,"settings","store"),{storeName:f.get("storeName").trim(),whatsapp:f.get("whatsapp").trim(),email:f.get("email").trim(),currency:"USD",updatedAt:serverTimestamp()},{merge:true});$("#settingsMessage").textContent="تم حفظ الإعدادات ✅"};
async function loadSettings(){const s=await getDoc(doc(db,"settings","store"));if(s.exists()){const p=s.data();settingsForm.storeName.value=p.storeName||"DIGITAL EMDZ";settingsForm.whatsapp.value=p.whatsapp||"+213770913494";settingsForm.email.value=p.email||"digitalemdz@gmail.com"}}
