(()=>{
const A={"الرئيسية":"Home","المنتجات":"Products","الدفع":"Payments","من نحن":"About Us","الخدمات":"Services","اتصل بنا":"Contact Us","الإدارة":"Admin","المتجر":"Store","واتساب":"WhatsApp","البريد الإلكتروني":"Email","كل شيء في مكانه":"Everything in one place","تصفح المنتجات":"Browse Products","طرق الدفع":"Payment Methods","اطلب خدمة":"Request a Service","التواصل مع البائع":"Contact the seller","مشاركة المنتج":"Share product","جاري تجهيز المنتجات...":"Loading products...","لحظات وسيتم عرض المنتجات هنا.":"Your products will appear here shortly.","رؤيتنا":"Our Vision","مهمتنا":"Our Mission","دعمنا":"Our Support","الاسم الكامل":"Full name","رقم الهاتف / واتساب (اختياري)":"Phone / WhatsApp (optional)","اختر نوع الخدمة":"Choose service type","إرسال طلب الخدمة":"Send service request","Home":"الرئيسية","Products":"المنتجات","Payments":"الدفع","About Us":"من نحن","Services":"الخدمات","Contact Us":"اتصل بنا","Admin":"الإدارة","Store":"المتجر","WhatsApp":"واتساب","Email":"البريد الإلكتروني","Everything in one place":"كل شيء في مكانه","Browse Products":"تصفح المنتجات","Payment Methods":"طرق الدفع","Request a Service":"اطلب خدمة","Contact the seller":"التواصل مع البائع","Share product":"مشاركة المنتج","Loading products...":"جاري تجهيز المنتجات...","Your products will appear here shortly.":"لحظات وسيتم عرض المنتجات هنا.","Our Vision":"رؤيتنا","Our Mission":"مهمتنا","Our Support":"دعمنا","Full name":"الاسم الكامل","Phone / WhatsApp (optional)":"رقم الهاتف / واتساب (اختياري)","Choose service type":"اختر نوع الخدمة","Send service request":"إرسال طلب الخدمة"};
const reverse={};for(const k in A){if(!reverse[A[k]])reverse[A[k]]=k}
let lang=localStorage.getItem('demdz_lang')||'ar';
function walk(dict){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){const t=n.nodeValue.trim();if(dict[t])n.nodeValue=n.nodeValue.replace(t,dict[t])}document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(e=>{if(dict[e.placeholder])e.placeholder=dict[e.placeholder]});document.querySelectorAll('option').forEach(e=>{const t=e.textContent.trim();if(dict[t])e.textContent=dict[t]})}
function add(){if(document.getElementById('langToggle'))return;const a=document.querySelector('.actions');if(!a)return;const b=document.createElement('button');b.id='langToggle';b.type='button';b.className='admin';b.textContent=lang==='en'?'العربية':'English';b.onclick=()=>{lang=lang==='en'?'ar':'en';apply()};a.prepend(b)}
function apply(){document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';walk(lang==='en'?A:reverse);const b=document.getElementById('langToggle');if(b)b.textContent=lang==='en'?'العربية':'English';localStorage.setItem('demdz_lang',lang)}
function init(){add();apply()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();