(()=>{
const A={
"الرئيسية":"Home","المنتجات":"Products","الدفع":"Payments","وسائل الدفع":"Payment Methods","من نحن":"About Us","الخدمات":"Services","اتصل بنا":"Contact Us","الإدارة":"Admin","المتجر":"Store","واتساب":"WhatsApp","البريد":"Email",
"✨ حلول رقمية جاهزة — ابدأ اليوم ووفّر وقتك":"✨ Ready digital solutions — Start today and save time",
"🔥 DIGITAL EMDZ • منتجات رقمية":"🔥 DIGITAL EMDZ • Digital Products",
"اكتشف عالم":"Discover the world of","المنتجات الرقمية.":"digital products.","كل شيء في مكانه":"Everything in one place","منتجات رقمية":"Digital Products","المنتجات":"Products","طرق الدفع":"Payment Methods","الخدمات":"Services","اتصل بنا":"Contact Us",
"قوالب، مخططات، كتب إلكترونية وأدوات رقمية تساعدك على تنظيم عملك، توفير وقتك وتحويل أفكارك إلى إنجاز.":"Templates, planners, ebooks and digital tools that help you organize your work, save time and turn ideas into results.",
"تصفح المنتجات":"Browse Products","اطلب خدمة":"Request a Service","منتجاتنا الرقمية":"Our Digital Products",
"اختر المنتج الذي تريده واضغط «شراء عبر واتساب». اكتب اسمك فقط، وسيصلنا طلبك مباشرة. سنتواصل معك ونرسل لك وسيلة الدفع المناسبة.":"Choose the product you want and contact us on WhatsApp. Enter your name only and we will receive your request directly. We will contact you and send you the suitable payment method.",
"الشراء بسيط:":"Simple purchase:","اختر المنتج ← اكتب اسمك ← يصلنا طلبك على واتساب ← نتواصل معك لإتمام الدفع.":"Choose the product ← enter your name ← your request reaches us on WhatsApp ← we contact you to complete payment.",
"جاري تجهيز المنتجات...":"Loading products...","لحظات وسيتم عرض المنتجات هنا.":"Your products will appear here shortly.",
"وسائل الدفع المتاحة":"Available Payment Methods","هذه الصفحة تعرض وسائل الدفع المتاحة فقط. عند شراء منتج، تواصل مع البائع عبر واتساب ليعطيك طريقة الدفع المناسبة.":"This page only shows available payment methods. When buying a product, contact the seller on WhatsApp for the suitable payment method.",
"الدفع عبر حساب Binance.":"Payment through Binance.","الدفع عبر حساب RedotPay.":"Payment through RedotPay.","التحويل البنكي — RIB":"Bank Transfer — RIB","التحويل البنكي عبر رقم الحساب RIB.":"Bank transfer using the RIB account number.","الدفع مباشرة عبر PayPal":"Pay directly via PayPal","اضغط هنا لفتح صفحة الدفع مباشرة في PayPal.":"Click here to open the PayPal payment page.","💳 الدفع الآن عبر PayPal":"💳 Pay now with PayPal",
"يمكن إدارة وسائل الدفع من لوحة الإدارة، بما في ذلك الاسم والحساب والتعليمات والصور وحالة التفعيل.":"Payment methods can be managed from the admin panel, including name, account, instructions, images and activation status.",
"رؤيتنا":"Our Vision","مهمتنا":"Our Mission","دعمنا":"Our Support","للاستفسارات والطلبات والدعم، تواصل معنا مباشرة.":"For questions, requests and support, contact us directly.","تواصل معنا مباشرة":"Contact us directly","البريد الإلكتروني":"Email","اضغط على الزر لفتح Gmail مباشرة":"Click the button to open Gmail directly","إرسال رسالة عبر Gmail":"Send a message via Gmail",
"اطلب خدمة مخصصة":"Request a Custom Service","الخدمات التي تظهر هنا يتم التحكم بها من لوحة الإدارة. يمكنك إظهار أو إخفاء أي خدمة في أي وقت.":"Services shown here are managed from the admin panel. You can show or hide any service at any time.","الاسم الكامل":"Full name","رقم الهاتف / واتساب (اختياري)":"Phone / WhatsApp (optional)","اختر نوع الخدمة":"Choose service type","تصميم منتج رقمي":"Digital product design","تعديل قالب":"Template editing","تصميم Canva":"Canva design","إنشاء متجر إلكتروني":"E-commerce store creation","كتاب إلكتروني / PDF":"E-book / PDF","خدمة مخصصة أخرى":"Other custom service","اشرح لنا ما تحتاجه بالتفصيل...":"Tell us what you need in detail...","سنستخدم بياناتك فقط للتواصل معك بخصوص طلب الخدمة.":"We will only use your information to contact you about your service request.","إرسال طلب الخدمة":"Send service request",
"اضغط «التواصل مع البائع» وسيتم فتح واتساب مباشرة للتواصل مع البائع.":"Click “Contact the seller” to open WhatsApp directly.","التواصل مع البائع":"Contact the seller","مشاركة المنتج":"Share product","نسخ الرابط":"Copy link","تم نسخ رابط المنتج بنجاح ✅":"Product link copied successfully ✅","تعذر نسخ الرابط":"Could not copy the link","المنتج غير موجود":"Product not found","المنتج غير موجود أو غير متاح":"Product not found or unavailable","تعذر تحميل المنتج":"Could not load product","حاول مرة أخرى لاحقًا.":"Please try again later.","العودة للمنتجات":"Back to products","Discover • Create • Grow":"Discover • Create • Grow",
"Home":"الرئيسية","Products":"المنتجات","Payments":"الدفع","Payment Methods":"وسائل الدفع","About Us":"من نحن","Services":"الخدمات","Contact":"اتصل بنا","Contact Us":"اتصل بنا","Admin":"الإدارة","Store":"المتجر","WhatsApp":"واتساب","Email":"البريد الإلكتروني","Ready Digital Products":"منتجات رقمية جاهزة",
"Ready digital solutions — Start today and save time":"حلول رقمية جاهزة — ابدأ اليوم ووفّر وقتك","Discover the world of":"اكتشف عالم","digital products.":"المنتجات الرقمية.","Everything in one place":"كل شيء في مكانه","Digital Products":"منتجات رقمية","Browse Products":"تصفح المنتجات","Request a Service":"اطلب خدمة","Simple purchase:":"الشراء بسيط:","Loading products...":"جاري تجهيز المنتجات...","Your products will appear here shortly.":"لحظات وسيتم عرض المنتجات هنا.","Available Payment Methods":"وسائل الدفع المتاحة","Bank Transfer — RIB":"التحويل البنكي — RIB","Pay directly via PayPal":"الدفع مباشرة عبر PayPal","Our Vision":"رؤيتنا","Our Mission":"مهمتنا","Our Support":"دعمنا","For questions, requests and support, contact us directly.":"للاستفسارات والطلبات والدعم، تواصل معنا مباشرة.","Contact us directly":"تواصل معنا مباشرة","Request a Custom Service":"اطلب خدمة مخصصة","Full name":"الاسم الكامل","Choose service type":"اختر نوع الخدمة","Phone / WhatsApp (optional)":"رقم الهاتف / واتساب (اختياري)","Digital product design":"تصميم منتج رقمي","Template editing":"تعديل قالب","Canva design":"تصميم Canva","E-commerce store creation":"إنشاء متجر إلكتروني","E-book / PDF":"كتاب إلكتروني / PDF","Other custom service":"خدمة مخصصة أخرى","Send service request":"إرسال طلب الخدمة","Contact the seller":"التواصل مع البائع","Share product":"مشاركة المنتج","Copy link":"نسخ الرابط","Back to products":"العودة للمنتجات","Product not found":"المنتج غير موجود","Product not found or unavailable":"المنتج غير موجود أو غير متاح","Could not load product":"تعذر تحميل المنتج","Please try again later.":"حاول مرة أخرى لاحقًا"
};
const reverse={};Object.entries(A).forEach(([ar,en])=>{if(!reverse[en])reverse[en]=ar});
let lang=localStorage.getItem('demdz_lang')||'ar';
const walk=(root,dict)=>{const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{const t=n.nodeValue.trim();if(dict[t])n.nodeValue=n.nodeValue.replace(t,dict[t])});root.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(el=>{if(dict[el.placeholder])el.placeholder=dict[el.placeholder]});root.querySelectorAll('option').forEach(el=>{const t=el.textContent.trim();if(dict[t])el.textContent=dict[t]})};
const apply=()=>{const dict=lang==='en'?A:reverse;document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';walk(document.body,dict);const b=document.getElementById('langToggle');if(b)b.textContent=lang==='en'?'العربية':'English';document.body.classList.toggle('lang-en',lang==='en');localStorage.setItem('demdz_lang',lang)};
const add=()=>{if(document.getElementById('langToggle'))return;const actions=document.querySelector('.actions');if(!actions)return;const b=document.createElement('button');b.id='langToggle';b.type='button';b.className='admin';b.style.cssText='font-weight:900;min-width:88px';b.textContent=lang==='en'?'العربية':'English';b.onclick=()=>{lang=lang==='en'?'ar':'en';apply()};actions.prepend(b)};
const init=()=>{add();apply()};
new MutationObserver(()=>{add();apply()}).observe(document.body,{childList:true,subtree:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();